import type { Metadata } from "next"
import { Geist, Geist_Mono,Noto_Sans } from "next/font/google"
import "./globals.css"
import { Header } from "./components/Header/Header"
import { Sidebar } from "./components/Sidebar/Sidebar"
import { Footer } from "./components/Footer/Footer"
import style from './layout.module.css';

 

const notoSans = Noto_Sans({
  weight: ['300', '400', '500', '700'],
  subsets: ['cyrillic', 'latin'],
  variable: '--font-noto',
  display: 'swap',
});

 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${notoSans.variable} h-full antialiased`}>
      <body className="min-h-full m-0 p-0 bg-[#F5F6F8]">
        <div className={style.wrapper}>
          <Header className={style.header} />
          <Sidebar className={style.sidebar} />
          <main className={style.body}>{children}</main>
          <Footer className={style.footer} />
        </div>
      </body>
    </html>
  );
}
